macro( ensure_lib_loads_symbol target symbol)
    if (MSVC)
      target_link_libraries(${target} PUBLIC "/INCLUDE:${symbol}")
    else()
      target_link_libraries(${target} PUBLIC "-u ${symbol}")
    endif()
endmacro()
