name: colcon workspace

on: [push, pull_request]

jobs:
  build:
    # test multiple Ubuntu and ROS distributions
    # https://github.com/ros-tooling/setup-ros#iterating-on-all-ros-distributions-for-all-platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - docker_image: ubuntu:20.04
            ros_distribution: noetic
            ros_version: 1

          - docker_image: ubuntu:22.04
            ros_distribution: humble
            ros_version: 2

          - docker_image: ubuntu:24.04
            ros_distribution: jazzy
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7

      - name: ROS 1 CI Action
        if: ${{ matrix.ros_version == 1 }}
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: pangolin
          target-ros1-distro: ${{ matrix.ros_distribution }}

      - name: ROS 2 CI Action
        if: ${{ matrix.ros_version == 2 }}
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: pangolin
          target-ros2-distro: ${{ matrix.ros_distribution }}
