name: format

on:
  push:
    branches: [ master, 23.04-beta ]
  pull_request:

  workflow_dispatch:

jobs:
  pre-commit-check:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
